New contributor victor
cardinalhealthcare/mediq-app pull request #14
Opened 2024-01-30 01:58 UTC by vbello-tech

Organizations.

2024-01-31 11:47 UTC, vbello-tech commented
New changes to organisation.

2024-02-19 10:40 UTC, ourcardinalhealth requested changes
you have reused an old branch for this pr
this pr should be created under a new branch the describes what you've worked on

2024-02-19 10:40 UTC, ourcardinalhealth commented on mediq/settings.py
> +    'organizations',
hi @vbello-tech 
let's use british english across the app. "s" instead of "z"
oraganisation, instead of organization

2024-02-19 10:40 UTC, ourcardinalhealth commented on mediq/settings.py
> +    'organizations',
ignore this. i can see you've used that across the entire application. we'll stick with american english

2024-02-20 04:48 UTC, vbello-tech commented
I will be closing this pr because it was meant for another branch that i have created.

2024-02-20 04:48 UTC, closed without merging